### ISSUE TITLE
CTR模式提示AssertionError: check input type

### ISSUE THREAD

**Issue by lu-xianseng** [DonggeunKwon/aes#1]
进行CTR模式加密，报错，不知道什么原因
import aes

key = b'T0VN5a6a5Yi25bmz'
iv = b'b2Vt5a6a5Yi25bmz'

cipher = aes.aes(
    masterkey=key,
    keysize=128,
    mode='CTR',
    padding='PKCS#7',
    iv=iv
)

提示：
  File "/home/lxs/Documents/工作第一/code/oem-auto-test/venv/lib/python3.7/site-packages/aes/_aes.py", line 35, in __init__
    iv)
  File "/home/lxs/Documents/工作第一/code/oem-auto-test/venv/lib/python3.7/site-packages/aes/utils/_check_tools.py", line 20, in check_para
    mk = int2arr8bit(masterkey, keysize//8)
  File "/home/lxs/Documents/工作第一/code/oem-auto-test/venv/lib/python3.7/site-packages/aes/utils/_format_tools.py", line 9, in int2arr8bit
    assert type(Int)==int, "check input type"
AssertionError: check input type

**Comment by donggeunkwon** [comment]
Thank you for your notice!

Bytes type cannot be used as input yet. 
Therefore, you should change the format of key and iv. You can fix it using aes.utils, like this:

```python
import aes

key = b'T0VN5a6a5Yi25bmz'
iv = b'b2Vt5a6a5Yi25bmz'

# add this; you should change the type of data (bytes -> int)
key_int = aes.utils.bytes2int(key)
iv_int = aes.utils.bytes2int(iv)

cipher = aes.aes(
masterkey=key_int,
keysize=128,
mode='CTR',
padding='PKCS#7',
iv=iv_int
)

# try yours, but note that ONLY array with 8-bit data as elements is possible!
pt = [0] * 65

# enc/dec
ct = cipher.dec(cipher.enc(pt))
```

**Comment by lu-xianseng** [comment]
> Thank you for your notice!
> 
> Bytes type cannot be used as input yet. Therefore, you should change the format of key and iv. You can fix it using aes.utils, like this:
> 
> ```python
> import aes
> 
> key = b'T0VN5a6a5Yi25bmz'
> iv = b'b2Vt5a6a5Yi25bmz'
> 
> # add this; you should change the type of data (bytes -> int)
> key_int = aes.utils.bytes2int(key)
> iv_int = aes.utils.bytes2int(iv)
> 
> cipher = aes.aes(
> masterkey=key_int,
> keysize=128,
> mode='CTR',
> padding='PKCS#7',
> iv=iv_int
> )
> 
> # try yours, but note that ONLY array with 8-bit data as elements is possible!
> pt = [0] * 65
> 
> # enc/dec
> ct = cipher.dec(cipher.enc(pt))
> ```

Thanks your help!
